spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf8&useSSL=true
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/test2?characterEncoding=utf8&useSSL=true
    three:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/test3?characterEncoding=utf8&useSSL=true
