package com.lingbang.mapper;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.OID
     *
     * @mbg.generated
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.USERNAME
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.TELNO
     *
     * @mbg.generated
     */
    private String telno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.PHONENO
     *
     * @mbg.generated
     */
    private String phoneno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.CREDITNO
     *
     * @mbg.generated
     */
    private String creditno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.SEX
     *
     * @mbg.generated
     */
    private Short sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.BIRTHDAY
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.OWNEHOUSE
     *
     * @mbg.generated
     */
    private String ownehouse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.OWNEPRO
     *
     * @mbg.generated
     */
    private String ownepro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.CLASSES
     *
     * @mbg.generated
     */
    private Short classes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.OID
     *
     * @return the value of t_users.OID
     *
     * @mbg.generated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.OID
     *
     * @param oid the value for t_users.OID
     *
     * @mbg.generated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.USER_ID
     *
     * @return the value of t_users.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.USER_ID
     *
     * @param userId the value for t_users.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.USERNAME
     *
     * @return the value of t_users.USERNAME
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.USERNAME
     *
     * @param username the value for t_users.USERNAME
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.PASSWORD
     *
     * @return the value of t_users.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.PASSWORD
     *
     * @param password the value for t_users.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.NAME
     *
     * @return the value of t_users.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.NAME
     *
     * @param name the value for t_users.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.TELNO
     *
     * @return the value of t_users.TELNO
     *
     * @mbg.generated
     */
    public String getTelno() {
        return telno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.TELNO
     *
     * @param telno the value for t_users.TELNO
     *
     * @mbg.generated
     */
    public void setTelno(String telno) {
        this.telno = telno == null ? null : telno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.PHONENO
     *
     * @return the value of t_users.PHONENO
     *
     * @mbg.generated
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.PHONENO
     *
     * @param phoneno the value for t_users.PHONENO
     *
     * @mbg.generated
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno == null ? null : phoneno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.CREDITNO
     *
     * @return the value of t_users.CREDITNO
     *
     * @mbg.generated
     */
    public String getCreditno() {
        return creditno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.CREDITNO
     *
     * @param creditno the value for t_users.CREDITNO
     *
     * @mbg.generated
     */
    public void setCreditno(String creditno) {
        this.creditno = creditno == null ? null : creditno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.ADDRESS
     *
     * @return the value of t_users.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.ADDRESS
     *
     * @param address the value for t_users.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.SEX
     *
     * @return the value of t_users.SEX
     *
     * @mbg.generated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.SEX
     *
     * @param sex the value for t_users.SEX
     *
     * @mbg.generated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.BIRTHDAY
     *
     * @return the value of t_users.BIRTHDAY
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.BIRTHDAY
     *
     * @param birthday the value for t_users.BIRTHDAY
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.OWNEHOUSE
     *
     * @return the value of t_users.OWNEHOUSE
     *
     * @mbg.generated
     */
    public String getOwnehouse() {
        return ownehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.OWNEHOUSE
     *
     * @param ownehouse the value for t_users.OWNEHOUSE
     *
     * @mbg.generated
     */
    public void setOwnehouse(String ownehouse) {
        this.ownehouse = ownehouse == null ? null : ownehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.OWNEPRO
     *
     * @return the value of t_users.OWNEPRO
     *
     * @mbg.generated
     */
    public String getOwnepro() {
        return ownepro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.OWNEPRO
     *
     * @param ownepro the value for t_users.OWNEPRO
     *
     * @mbg.generated
     */
    public void setOwnepro(String ownepro) {
        this.ownepro = ownepro == null ? null : ownepro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.CLASSES
     *
     * @return the value of t_users.CLASSES
     *
     * @mbg.generated
     */
    public Short getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.CLASSES
     *
     * @param classes the value for t_users.CLASSES
     *
     * @mbg.generated
     */
    public void setClasses(Short classes) {
        this.classes = classes;
    }
}